Namespace ensure_packages()
voxpupuli/puppet-virtualbox pull request #151
Opened 2024-04-12 00:36 UTC by smortex

The ensure_packages() function is deprecated and we should use
stdlib::ensure_packages() instead.

2024-04-12 05:09 UTC, TheMeier approved these changes

2024-04-12 09:07 UTC, alexjfisher requested changes
You'd want to bump the dependency in metadata.json too.

2024-04-12 19:55 UTC, smortex commented
> You'd want to bump the dependency in metadata.json too.

Good catch, I fixed this in multiple places and it slept through!  PR updated!

2024-04-13 06:31 UTC, TheMeier approved these changes

2025-06-24 14:27 UTC, merged